In [17]:
import pandas as pd
import json

In [ ]:
def fra_json_til_dataframe(filnavn):
    with open(filnavn, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Henter observasjonene
    observationer = data.get("data", [])
    
    # Definerer tomme rader først
    rader = []

    for obs in observationer:
        source_id = obs.get('sourceId', None)
        reference_time = obs.get('referenceTime', None)


    # For hver observasjon kan vi lage en rad med informasjonen vi trenger
        for observation in obs.get('observations', []):
            rader.append({
                'sourceId': source_id,
                'referenceTime': reference_time,
                'elementId': observation.get('elementId', None),
                'value': observation.get('value', None),
                'unit': observation.get('unit', None),
                'timeOffset': observation.get('timeOffset', None),
                'performanceCategory': observation.get('performanceCategory', None)
            })
    
    # Lag en Pandas DataFrame
    df = pd.DataFrame(rader)
    return df

In [ ]:
# Les fra JSON - nedbør
df_nedbor = fra_json_til_dataframe("frost_nedbor.json")


# Skriv ut dataene i tabell
print("Nedbør:")
display(df_nedbor)

Nedbør:

,sourceId,referenceTime,elementId,value,unit,timeOffset,performanceCategory
0,SN18700:0,2023-01-01T00:00:00.000Z,sum(precipitation_amount P1D),0.0,mm,PT18H,C
1,SN18700:0,2023-01-01T00:00:00.000Z,sum(precipitation_amount P1D),0.0,mm,PT6H,C
2,SN18700:0,2023-01-02T00:00:00.000Z,sum(precipitation_amount P1D),0.6,mm,PT18H,C
3,SN18700:0,2023-01-02T00:00:00.000Z,sum(precipitation_amount P1D),0.6,mm,PT6H,C
4,SN18700:0,2023-01-03T00:00:00.000Z,sum(precipitation_amount P1D),0.0,mm,PT18H,C
...,...,...,...,...,...,...,...
723,SN18700:0,2023-12-28T00:00:00.000Z,sum(precipitation_amount P1D),2.2,mm,PT6H,C
724,SN18700:0,2023-12-29T00:00:00.000Z,sum(precipitation_amount P1D),6.3,mm,PT18H,C
725,SN18700:0,2023-12-29T00:00:00.000Z,sum(precipitation_amount P1D),5.5,mm,PT6H,C
726,SN18700:0,2023-12-30T00:00:00.000Z,sum(precipitation_amount P1D),0.4,mm,PT18H,C
727,SN18700:0,2023-12-30T00:00:00.000Z,sum(precipitation_amount P1D),1.8,mm,PT6H,C

In [16]:
#Les fra JSON - temp
df_temp = fra_json_til_dataframe("frost_temp.json")


#Skriv ut på tabell:
print("Temperatur:")
display(df_temp)

Temperatur:

,sourceId,referenceTime,elementId,value,unit,timeOffset,performanceCategory
0,SN18700:0,1980-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),5.400,degC,PT0H,C
1,SN18700:0,1981-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),5.200,degC,PT0H,C
2,SN18700:0,1982-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.200,degC,PT0H,C
3,SN18700:0,1983-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.000,degC,PT0H,C
4,SN18700:0,1984-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.700,degC,PT0H,C
5,SN18700:0,1985-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),4.400,degC,PT0H,C
6,SN18700:0,1986-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),5.500,degC,PT0H,C
7,SN18700:0,1987-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),4.600,degC,PT0H,C
8,SN18700:0,1988-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.600,degC,PT0H,C
9,SN18700:0,1989-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.700,degC,PT0H,C
10,SN18700:0,1990-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.800,degC,PT0H,C
11,SN18700:0,1991-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.700,degC,PT0H,C
12,SN18700:0,1992-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.100,degC,PT0H,C
13,SN18700:0,1993-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.100,degC,PT0H,C
14,SN18700:0,1994-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.300,degC,PT0H,C
15,SN18700:0,1995-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.400,degC,PT0H,C
16,SN18700:0,1996-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),5.300,degC,PT0H,C
17,SN18700:0,1997-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.200,degC,PT0H,C
18,SN18700:0,1998-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.400,degC,PT0H,C
19,SN18700:0,1999-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.800,degC,PT0H,C
20,SN18700:0,2000-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.800,degC,PT0H,C
21,SN18700:0,2001-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.200,degC,PT0H,C
22,SN18700:0,2002-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.000,degC,PT0H,C
23,SN18700:0,2003-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.000,degC,PT0H,C
24,SN18700:0,2004-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.200,degC,PT0H,C
25,SN18700:0,2005-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.400,degC,PT0H,C
26,SN18700:0,2006-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.700,degC,PT0H,C
27,SN18700:0,2007-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.183,degC,PT0H,C
28,SN18700:0,2008-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.500,degC,PT0H,C
29,SN18700:0,2009-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.700,degC,PT0H,C
30,SN18700:0,2010-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),4.842,degC,PT0H,C
31,SN18700:0,2011-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.383,degC,PT0H,C
32,SN18700:0,2012-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.567,degC,PT0H,C
33,SN18700:0,2013-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.708,degC,PT0H,C
34,SN18700:0,2014-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),8.292,degC,PT0H,C
35,SN18700:0,2015-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.625,degC,PT0H,C
36,SN18700:0,2016-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.300,degC,PT0H,C
37,SN18700:0,2017-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),6.942,degC,PT0H,C
38,SN18700:0,2018-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.750,degC,PT0H,C
39,SN18700:0,2019-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),7.283,degC,PT0H,C
40,SN18700:0,2020-01-01T00:00:00.000Z,best_estimate_mean(air_temperature P1Y),8.717,degC,PT0H,C